# Taps
tap "discoteq/discoteq" # for "flock"
tap "heroku/brew" # for "heroku"

# Std brew packages
brew "ack"
brew "awscli"
brew "bash"
brew "carlocab/personal/unrar"
brew "colordiff"
brew "coreutils"
brew "crystal"
brew "crystal-icr"
brew "elixir"
brew "fd"
brew "findutils"
brew "flock"
brew "fping"
brew "fswatch"
brew "fzf"
brew "gh"
brew "gist"
brew "glances"
brew "gnu-tar"
brew "go"
brew "gpg"
brew "graphviz"
brew "heroku"
brew "hub"
brew "imagemagick"
brew "java"
brew "jdupes"
brew "jq"
brew "kubectl"
brew "libmagic"
brew "lua@5.1"
brew "luarocks"
brew "moreutils"
brew "mplayer"
brew "ncdu"
brew "nmap"
brew "nvm"
brew "openssh"
brew "openssl"
brew "overmind"
brew "pcre"
brew "pinentry-mac"
#brew "postgresql"
brew "pstree"
brew "pwgen"
brew "pyenv"
brew "redis"
brew "rename"
brew "selecta"
brew "teleport"
brew "telnet"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"

# Install Casks
cask "1password"
cask "adobe-acrobat-reader"
cask "alfred"
cask "aws-vault"
cask "contexts"
cask "dash"
cask "docker"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "google-drive-file-stream"
cask "hma-pro-vpn"
cask "iterm2"
cask "little-snitch"
cask "mplayerx"
#cask "pencil"
#cask "postman"
cask "pycharm"
#cask "rubymine"
cask "skitch"
cask "slack"
#cask "sketch"
#cask "sip"
#cask "sourcetree"
cask "spectacle"
#cask "spotify"
#cask "textual"
#cask "textmate"
#cask "transmit"
cask "visual-studio-code"
cask "zoom"

# post-install for some packages
# $(brew --prefix)/opt/fzf/install
